### ISSUE TITLE
note.fromEventLog failing from missing /node_modules/aztec.js/dist/mcl_c.wasm file

### ISSUE THREAD

**Issue by naddison36** [AztecProtocol/aztec-v1#535]
## Expected Behaviour

To be able to run the following code using node.js
```js
const note = require("aztec.js").note
const metadata = "0x1c6a72f049e538bb2c272529d626245da8e4380b3b78a848e7f35d54b6c4e7da27a387ec17338eefe6ab0c287807df0fd4437a3ad83190e0195e13505b609110dd6feecda50f75d733cf956c57e786976af334a9670c9dc27ce90139db3d1cf901"
note.fromEventLog(
  metadata,
  "0x0000000000000000000000000000000000000000000000000000000000000003"
).then(note1 => {
  console.log(`Note owner: ${note1.owner}`)
})
```

## Current Behaviour

I get the following error when I run the above
```
/Users/nick/.nvm/versions/node/v12.11.1/bin/node /Users/nick/workspaces/aztec-test/index.js
{ Error: ENOENT: no such file or directory, open '/Users/nick/workspaces/aztectest/node_modules/aztec.js/dist/mcl_c.wasm'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at Object.process.env.WEBPACK_WEB_ENV.t.read (/Users/nick/workspaces/aztectest/node_modules/aztec.js/dist/bundle.node.js:9:13919)
    at Object.process.env.WEBPACK_WEB_ENV.t.readBinary (/Users/nick/workspaces/aztectest/node_modules/aztec.js/dist/bundle.node.js:9:13986)
    at u (/Users/nick/workspaces/aztectest/node_modules/aztec.js/dist/bundle.node.js:9:18427)
    at t.wasmBinary.s.function.fetch.credentials (/Users/nick/workspaces/aztectest/node_modules/aztec.js/dist/bundle.node.js:9:19529)
    at new Promise (<anonymous>)
    at d (/Users/nick/workspaces/aztectest/node_modules/aztec.js/dist/bundle.node.js:9:19500)
    at f (/Users/nick/workspaces/aztectest/node_modules/aztec.js/dist/bundle.node.js:9:19965)
    at Object.t.asm (/Users/nick/workspaces/aztectest/node_modules/aztec.js/dist/bundle.node.js:9:20949)
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path:
   '/Users/nick/workspaces/aztec-test/node_modules/aztec.js/dist/mcl_c.wasm' }
```

## Possible Solution

`node_modules/aztec.js/dist/mcl_c.wasm` needs to be included in the aztec.js bundle or referenced from the `@aztec/bn128` module

My current workaround is to run the following to get the above code to work
```bash
cp ./node_modules/@aztec/bn128/dist/mcl_c.wasm ./node_modules/aztec.js/dist/mcl_c.wasm
```

## Your Environment

-   AZTEC packages and their versions: aztec.js 0.18.0
-   Node and yarn version: node v12.11.1
-   Operating System and version: macOS 10.15.5

**Comment by ArnSch** [comment]
Ah! Sorry, that's my bad. Must have broken the node build when trying to not include that file in the browser build. Will look to fix.

**Comment by naddison36** [comment]
Thanks @ArnSch. While you are at it, it'd be good for node.js to not be minified. That way developers can step through the code when debugging.
Cheers
